'use client'

/**
 * Realistic Try-On modal (Phase 1b)
 *
 * Sends your saved full-body photo + a garment image to the AI try-on API and
 * shows the result. Your photo is stored locally and reused, so you only upload
 * it once. Needs FASHN_API_KEY configured on the server.
 */

import { useRef, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { Loader2, Upload, RotateCcw, Download, Sparkles, AlertCircle, ImageIcon } from 'lucide-react'
import {
  getBodyPhoto, saveBodyPhoto, downscalePhoto, runRealisticTryOn, type FashnCategory,
} from '@/lib/tryOn'

interface RealisticTryOnModalProps {
  open: boolean
  onClose: () => void
  garmentImage: string
  garmentName: string
  category: FashnCategory
}

type Stage = 'setup' | 'processing' | 'result' | 'error'

export function RealisticTryOnModal({ open, onClose, garmentImage, garmentName, category }: RealisticTryOnModalProps) {
  const fileRef = useRef<HTMLInputElement>(null)
  const [bodyPhoto, setBodyPhoto] = useState<string | null>(() => getBodyPhoto())
  const [stage, setStage] = useState<Stage>('setup')
  const [result, setResult] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [needsKey, setNeedsKey] = useState(false)

  async function handlePhoto(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    const dataUrl = await downscalePhoto(file)
    setBodyPhoto(dataUrl)
    saveBodyPhoto(dataUrl)
  }

  async function generate() {
    if (!bodyPhoto) return
    setStage('processing'); setError(null); setNeedsKey(false)
    const res = await runRealisticTryOn({ modelImage: bodyPhoto, garmentImage, category })
    if (res.resultImage) {
      setResult(res.resultImage)
      setStage('result')
    } else {
      setError(res.error ?? 'Try-on failed.')
      setNeedsKey(Boolean(res.needsApiKey))
      setStage('error')
    }
  }

  function close() {
    setStage('setup'); setResult(null); setError(null)
    onClose()
  }

  return (
    <Dialog open={open} onOpenChange={close}>
      <DialogContent className="max-w-md max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-primary" /> Realistic try-on
          </DialogTitle>
          <DialogDescription>See {garmentName} on you, generated by AI.</DialogDescription>
        </DialogHeader>

        {/* Garment being tried on */}
        <div className="flex items-center gap-3 bg-secondary/40 rounded-lg p-2">
          <img src={garmentImage} alt={garmentName} className="w-12 h-12 rounded-md object-cover border border-border/40" />
          <span className="text-sm">{garmentName}</span>
        </div>

        {stage === 'setup' && (
          <div className="space-y-4">
            <div className="aspect-[3/4] max-h-72 mx-auto rounded-xl bg-secondary/50 overflow-hidden flex items-center justify-center">
              {bodyPhoto ? (
                <img src={bodyPhoto} alt="Your photo" className="w-full h-full object-cover" />
              ) : (
                <div className="text-center p-6 text-muted-foreground">
                  <ImageIcon className="w-10 h-10 mx-auto mb-2 opacity-40" />
                  <p className="text-sm">Upload a full-body photo</p>
                </div>
              )}
            </div>
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1" onClick={() => fileRef.current?.click()}>
                <Upload className="w-4 h-4 mr-2" /> {bodyPhoto ? 'Change photo' : 'Upload photo'}
              </Button>
              <Button className="flex-1" onClick={generate} disabled={!bodyPhoto}>
                <Sparkles className="w-4 h-4 mr-2" /> Generate
              </Button>
            </div>
            <p className="text-xs text-muted-foreground text-center">
              Use a clear, front-facing full-body photo in good light. Your photo stays on your device and is sent only to generate the try-on.
            </p>
            <input ref={fileRef} type="file" accept="image/*" onChange={handlePhoto} className="hidden" />
          </div>
        )}

        {stage === 'processing' && (
          <div className="py-12 text-center">
            <Loader2 className="w-10 h-10 animate-spin text-primary mx-auto mb-3" />
            <p className="font-medium">Generating your try-on…</p>
            <p className="text-sm text-muted-foreground">This usually takes 10–30 seconds.</p>
          </div>
        )}

        {stage === 'result' && result && (
          <div className="space-y-3">
            <div className="aspect-[3/4] max-h-80 mx-auto rounded-xl overflow-hidden bg-secondary/50">
              <img src={result} alt="Try-on result" className="w-full h-full object-cover" />
            </div>
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1" onClick={() => setStage('setup')}>
                <RotateCcw className="w-4 h-4 mr-2" /> Try again
              </Button>
              <Button
                className="flex-1"
                onClick={() => {
                  const a = document.createElement('a')
                  a.href = result
                  a.download = `tryon-${garmentName.toLowerCase().replace(/\s+/g, '-')}.jpg`
                  a.click()
                }}
              >
                <Download className="w-4 h-4 mr-2" /> Save
              </Button>
            </div>
          </div>
        )}

        {stage === 'error' && (
          <div className="py-8 text-center space-y-3">
            <AlertCircle className="w-10 h-10 text-destructive mx-auto" />
            <p className="text-sm text-muted-foreground max-w-xs mx-auto">{error}</p>
            {needsKey && (
              <p className="text-xs text-muted-foreground max-w-xs mx-auto">
                Add <code className="font-mono">FASHN_API_KEY</code> to your environment to enable realistic try-on.
              </p>
            )}
            <Button variant="outline" onClick={() => setStage('setup')}>
              <RotateCcw className="w-4 h-4 mr-2" /> Back
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
